version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "8002:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
  app:
    image: bank-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_LIQUIBASE_ENABLED: true
    depends_on:
      - db
    networks:
      - backend
networks:
  backend: