server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:8001/postgres
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
    default-schema: public

